---
title: 'Today project'
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
body{
font-size: 12pt;
}
</style>

```{r exposure outcome setup, include=FALSE}
source(here::here("!libraries.R"))
source(here::here("!directories.R"))
source(here::here("!load_clean_data.R"))
source(here::here("!functions.R"))
source(here::here("analysis function_Multiple exposures and multiple outcomes analysis.R"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Mediation
```{r,results='asis'}
# overlapping_feature1 <- c("seq.10749.18", "seq.13485.20", "seq.18156.7",
#                          "seq.18173.11", "seq.18901.26", "seq.19570.12",
#                          "seq.19765.17", "seq.21144.160", "seq.21164.83",
#                          "seq.21231.3", "seq.21512.6", "seq.22398.5",
#                          "seq.23624.34", "seq.24226.30", "seq.24640.63",
#                          "seq.24708.7", "seq.25082.3", "seq.2750.3",
#                          "seq.2765.4", "seq.2829.19", "seq.4542.24",
#                          "seq.4551.72", "seq.4566.24", "seq.5354.11",
#                          "seq.5494.52", "seq.5638.23", "seq.6264.9",
#                          "seq.6491.59", "seq.8318.13", "seq.8355.80",
#                          "seq.8606.39", "seq.8923.94", "seq.9767.22",
#                          "seq.9875.107", "seq.9957.9")

# overlapping_feature <- c("seq.12821.6","seq.13429.3","seq.13651.54",
#                          "seq.21144.160", "seq.22398.5","seq.24640.63",
#                          "seq.24947.40", "seq.2765.4","seq.4551.72",
#                          "seq.6525.17","seq.7050.5","seq.8606.39",
#                          "seq.8891.7","seq.9991.112")

overlapping_feature <- c("seq.21144.160", "seq.22398.5","seq.24640.63",
                         "seq.2765.4", "seq.4551.72", "seq.8606.39")

med_res_df <- data.frame()

for(name in overlapping_feature){
  cat("### Section ", name, "\n")
  d2<-data_scaled %>% 
    dplyr::select(pfas_pfna, name, all_of(covars), daystomic, mic) %>% as.data.frame() %>%
    rename(mediator = name)
  # set.seed(1111)
  med <- CMAverse::cmest(data = d2, 
                         # model = "gformula",
                         model = "rb",
                         event = "mic",
                         exposure = "pfas_pfna",
                         mediator = "mediator", 
                         outcome = "daystomic",
                         basec = c("sex_male","agebase","serum_creat","dxtime"),
                         EMint = TRUE,
                         mreg = list("linear"), 
                         yreg = "coxph",
                         # astar = quantile(d2$pfas_pfna, probs = 0.9),
                         # a = quantile(d2$pfas_pfna, probs = 0.1),
                         astar = 0.5,
                         a = -0.5,
                         mval = list(0), 
                         # estimation = "imputation",
                         # inference = "bootstrap",
                         # nboot = 2
                         estimation = "paramfunc",
                         inference = "delta"
                         )
  print(summary(med))
  med_res_temp <-  med$effect.pe %>% as.data.frame() %>% rename(pe = ".") %>%
    cbind(med$effect.ci.low %>% as.data.frame() %>% rename(ci_low = ".") ) %>%
    cbind(med$effect.ci.high %>% as.data.frame() %>% rename(ci_high = ".")) %>%
    cbind(med$effect.pval %>% as.data.frame() %>% rename(pval = ".")) %>%
    mutate(feature_name = name) %>%
    rownames_to_column("Effect")%>%
    dplyr::select(feature_name, everything())
  
  # reg_res_temp <- med$reg.output$yreg$coefficients %>% data.frame()%>%
  #   rename(yreg_coef = ".") %>% t() %>% data.frame() %>%
  #   mutate(feature_name = name) %>%
  #   dplyr::select(feature_name, everything()) 
    
  # reg_res_df <- rbind(reg_res_df, reg_res_temp)
  med_res_df <- rbind(med_res_df,med_res_temp)
  cat("\n")
}

med_res_df1 <- med_res_df %>% tidylog::left_join(prot_metadata %>% 
                       dplyr::select(AptName, EntrezGeneSymbol),
                     by = c("feature_name"="AptName")) %>% 
  dplyr::select(feature_name, EntrezGeneSymbol, everything())

## sig total effect (n = 12)
med_res_df_te <- med_res_df1 %>%
  filter(Effect == "Rtnie"|Effect == "Rpnie") %>%
  filter(pval <0.05)

## filter those 12 mediators (check pm , they are all reasonable)

med_res_df_sig <- med_res_df1 %>%
  filter(feature_name %in% med_res_df_te$feature_name) %>%
  filter(Effect %in% c("Rte", "Rpnde", "Rtnie", "pm"))



# med_res_df_sig <- med_res_df1 %>% 
#   # filter(Effect %in% c("pm", "Rte") & pval < 0.05) %>%
#   filter(Effect %in% c("pm", "Rte")) 
#   # filter(pe >= 0) %>%
#   # group_by(feature_name) %>%
#   # mutate(n = n()) %>% 
#   # filter(n == 2)
 
write_csv(med_res_df_sig, fs::path(dir_results, "med_res_df.csv")) 
# write_csv(med_res_df_sig, fs::path(dir_results, "med_res_df.csv"))



rownames(reg_res_df) <- NULL
reg_res_df1 <- reg_res_df %>% tidylog::left_join(prot_metadata %>% 
                       dplyr::select(AptName, EntrezGeneSymbol),
                     by = c("feature_name"="AptName")) %>% 
  dplyr::select(feature_name, EntrezGeneSymbol, everything())


# note
# sig mediator: seq.21144.160,seq.22398.5,seq.2765.4,seq.21231.3(neg pm),seq.24226.30 (neg pm),seq.4551.72 (neg pm), seq.8923.94 (not sig pm)
# sig pm and sig te: seq.10749.18, seq.18173.11, seq.18901.26, seq.19570.12, seq.21144.160,seq.21512.6(big pm),seq.22398.5,seq.23624.34,seq.24708.7,seq.25082.3, seq.2750.3,seq.2765.4,seq.2829.19, seq.5494.52,seq.5638.23,seq.6264.9,seq.6491.59,seq.8355.80, seq.8606.39, seq.9767.22,seq.9957.9

# sig pm:
# sig te:seq.21164.83,seq.24640.63,seq.4542.24,seq.8923.94
# sig te and sig pm but neg: seq.21231.3,seq.24226.30,seq.4551.72,seq.4566.24, seq.8318.13

sig_te_pm <- c("seq.10749.18", "seq.18173.11", "seq.18901.26", 
               "seq.19570.12","seq.21144.160","seq.22398.5",
               "seq.23624.34","seq.24708.7","seq.25082.3",
               "seq.2750.3","seq.2765.4","seq.2829.19",
               "seq.5494.52","seq.5638.23","seq.6264.9",
               "seq.6491.59","seq.8355.80", "seq.8606.39",
               "seq.9767.22","seq.9957.9")

```

