---
title: 'Today project'
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
body{
font-size: 12pt;
}
</style>

```{r exposure outcome setup, include=FALSE}
source(here::here("!libraries.R"))
source(here::here("!directories.R"))
source(here::here("!load_clean_data.R"))
source(here::here("!functions.R"))
source(here::here("analysis function_Multiple exposures and multiple outcomes analysis.R"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Examine key variables, set in the load_clean_data file.
```{r define variables}
# Glucose Outcomes: 
outcome_glu
# Tubular Injury Biomarkers 
outcome_biomaker 
# PFAS names for analysis
(analysis_pfas_names <- c(pfas_names_all, "score", "score_pfsas", "score_pfcas")) 
# Covariates for primary analysis
covars
# Order of PFAS for figures
levels
```

# Survival Analysis
```{r run model}
## A. Set up for analysis ------
# Get the name of all PFAS exposure variables that were just created 
ind_vars <- data_scaled %>% 
  dplyr::select(
    #contains("median"),
    #contains("tertile"),
    #contains("quartile"),
    contains("score"), 
    contains("_sum"),
    all_of(pfas_names_all)) |> 
  colnames() %>%  
  tibble(exposure = .)

# Get the name of all outcome variables created 
dep_vars <- tibble(time = c(#"yrstohyp2", "yrstomic2",   #"yrstoglyc2",
  "daystohyp", "daystomic"),   #"daystoglyc",
  event = c(#"hyp", "mic",    #"glyc", 
    "hyp", "mic"))   #"glyc", 

# Get dataframe of all exposure outcome combinations
eo_comb <- list(pfas = ind_vars$exposure, event = dep_vars$event) %>%
  cross_df() %>% 
  left_join(dep_vars, by = "event", relationship = "many-to-many")

## B. Set covars ---------
covars2 <- c("sex_male", "agebase", "serum_creat", "dxtime")
# original covars:  "case1_control0", "sex_male", "agebase", "serum_creat"   
colnames(data_scaled[,1:30])

# Get the formula for all models
models <- eo_comb %>%
  mutate(covar = str_c(covars2, collapse = "+"),
         formula = str_c("Surv(", time , ",", event, ")", "~", pfas, "+", covar))

## C. Run the models -----
models$output <- map(models$formula,
                     ~coxph(as.formula(.), data = data_scaled) %>%
                       tidy(., conf.int = TRUE))

# Clean up results
pfas_survival_models <- models %>%
  unnest(output) %>%
  tidylog::filter(grepl("score", term) | 
                    grepl("pfas_", term) | 
                    grepl("_sum", term) & !grepl("quintile",term)) %>%
  rename_pfas() %>%
  mutate(HR = exp(estimate),
         exp_conf_high = exp(conf.high),
         exp_conf_low = exp(conf.low),
         sig = ifelse(p.value < 0.05, "Sig.", "Not Sig."), 
         ind_or_mix = if_else(str_detect(term, "score"), 
                              "Score", "Individual"), 
         functional_group = case_when(
           ind_or_mix == "Score" ~ "Score", 
           pfas  %in% c("PFOS", "PFHpS", "PFHxS") ~ "SA", 
           pfas == "NMeFOSAA" ~ "Other", 
           TRUE ~ "CA") |> 
           fct_relevel("CA", "SA", "Other", "Score"), 
         pfas = ifelse(pfas %in% levels, pfas, term), 
         pfas_chain = rename_pfas_with_chainlength(pfas_names_cleaned = pfas), 
         pfas_chain = order_pfas_by_chain_length(pfas_chain))
```

# Coefficient Plot
```{r coef plot}
## D. Plot results ------
# All results
(p <- pfas_survival_models %>%
   ggplot(aes(x = term,y = estimate, color = sig)) +
   geom_point(size = 1) +
   geom_errorbar(aes(ymin = conf.low,
                     ymax = conf.high),
                 width = 0) +
   geom_hline(yintercept = 0, linetype = 2) +
   facet_grid( ~ time, scales = "free") +
   ylab("Log HR (95% CI)") +
   theme(text = element_text(size = 10),
         axis.title.y = element_blank(),
         panel.background = element_rect(fill="white"),
         strip.background = element_rect(fill = "white"),
         axis.line.x = element_line(color = "black"),
         axis.line.y = element_line(color = "black"),
         legend.position = "none") +
   coord_flip() +
   scale_color_manual(values = c("grey", "red")))


pfas_survival_models |> 
  filter(str_detect(term, "pfcas")) |> 
  dplyr::select(pfas, event, p.value)

### i) Albuminuria ------
(fig1a_pfas_albuminuria <- pfas_survival_models %>%
   dplyr::filter(event == "mic", 
                 !(term %in% c("score_quintile", 
                                 "score_quartile", 
                                 "score_tertile", 
                                 "score_median1"))) %>% 
   # mutate(pfas_chain = fct_reorder(pfas_chain, estimate)) %>%
   ggplot(aes(y = fct_rev(pfas_chain), x = HR)) +
   geom_point(size = 1) +
   geom_errorbar(aes(xmin = exp_conf_low,
                     xmax = exp_conf_high),
                 width = 0) +
   geom_vline(xintercept = 1, linetype = 2) +
   facet_grid(functional_group ~ ., scales = "free", space = "free_y") +
   xlab("Hazard Ratio (95% CI)") +
   xlim(c(0, 9)) +
   theme(strip.text = element_blank(),
         axis.title.y = element_blank(),
         panel.background = element_rect(fill="white"),
         strip.background = element_rect(fill = "white"),
         axis.line.x = element_line(color = "black"),
         axis.line.y = element_line(color = "black"),
         legend.position = "none"))
```

# Meet in the middle
```{r meet in the middle}
## Meet in the middle analysis
(analysis_pfas_names <- c(pfas_names_all, "score_pfsas", "score_pfcas")) 
# JG removed overall PFAS burden score, becuase the heatmap looks better without it


# 1) Exposure-Mediator regressions ----------------
result_em <- epiomics::owas(df = data_scaled, 
                            var = "pfas_pfna", #analysis_pfas_names,
                            omics = omic_names, #prot_names,
                            covars = covars,
                            var_exposure_or_outcome = "exposure",
                            family = "gaussian",
                            confidence_level = 0.95, 
                            conf_int = TRUE)

# Calculate significance based on effective number of tests (42)
result_em <- result_em |> 
  mutate(omic_layer = if_else(feature_name %in% prot_names, "Proteomics", "Metabolomics")) |> 
  group_by(var_name, omic_layer) |>
  mutate(sig_efnum = if_else(p_value < (0.05/42), "Sig", "Not sig"), 
         adjusted_pval = p.adjust(p_value, method = "fdr"),
         sig_fdr = if_else(adjusted_pval < 0.2, "Sig", "Not sig")) |> 
  ungroup()

# Check seq.8032.23 (MCCD1)

## A. Clean results -----
# get name of all sig proteins
omic_names_sig <- result_em |> 
  dplyr::filter(p_value < 0.05)
omic_names_sig <- unique(omic_names_sig$feature_name)

# Select key columns, filter to significant omics only
result_em_sig <- result_em %>% 
  tidylog::filter(feature_name %in% omic_names_sig) |> 
  dplyr::select(omic_layer, var_name, feature_name, test_statistic,
                estimate, conf_low, conf_high, p_value, sig_efnum) |> 
  rename(estimate_em = estimate, 
         conf_low_em =  conf_low, 
         conf_high_em = conf_high,
         p_value_em = p_value, 
         test_statistic_em = test_statistic) 

length(unique(result_em_sig$feature_name))


# 2) Mediator-outcome regressions ----------------
ind_vars <- tibble(exposure = omic_names)
dep_vars <- tibble(time = c("daystomic"), event = c("mic"))

# Get exposure and outcome combinations
mo_comb <- list(omic = ind_vars$exposure, event = dep_vars$event) %>%
  cross_df() %>% 
  left_join(dep_vars, by = "event")

# Create combination of exposures and outcomes
mo_res_models <- mo_comb %>%
  mutate(covar = str_c(covars, collapse = "+"),
         formula = str_c("Surv(", time, ",", event, ")", "~", omic, "+", covar))

# Run all models
mo_res_models$output <- map(mo_res_models$formula,
                            ~coxph(as.formula(.),
                                   data = data_scaled) %>%
                              tidy(., conf.int = TRUE))

# Modify output
mo_res_models <- mo_res_models %>%
  unnest(output) %>%
  filter(grepl("seq", term)|grepl("met",term))%>%
  mutate(HR = exp(estimate),
         exp_conf_high = exp(conf.high),
         exp_conf_low = exp(conf.low),
         sig = ifelse(p.value < 0.05, "Sig.", "Not Sig.")) 

## A. Clean results ----
# Select key columns, filter significant only
result_mo_sig <- mo_res_models %>% 
  tidylog::filter(p.value < 0.05) %>%
  dplyr::select(omic, estimate, p.value, HR, exp_conf_high, exp_conf_low) |> 
  rename(feature_name = omic, 
         estimate_mo = estimate, 
         p.value_mo = p.value,
         HR_mo = HR,
         exp_conf_low_mo = exp_conf_low,
         exp_conf_high_mo = exp_conf_high)


# 3) Combine and analyze meet in middle --------------------
# Combine em and mo
mim_res <- tidylog::inner_join(result_em_sig, 
                               result_mo_sig, 
                               by = "feature_name")

# examine meet in middle proteins
mim_res <- mim_res |> 
  mutate(emxmo = estimate_em*estimate_mo, 
         max_p = if_else(p_value_em < p.value_mo, p.value_mo, p_value_em))

# Create cleaned PFAS name variable
mim_res <- mim_res |> 
  rename(pfas = var_name) |>
  rename_pfas() |>
  rename(pfas_name = pfas) 


## Combine with proteomics metadata ------
mim_res2 <- mim_res %>% 
  tidylog::left_join(prot_metadata, by = c("feature_name" = "AptName")) |> 
  tidylog::filter(Organism == "Human") 

# Coefficient plot HW-----
## result in Long format for plotting (HW)
mim_res_l <- mim_res2 %>% 
  dplyr::select(omic_layer:feature_name, EntrezGeneSymbol, 
                estimate_em:p_value_em) %>%
  rename_with(.cols = estimate_em:p_value_em,
              .fn = ~str_remove(., "_em") ) %>% 
  mutate(type = "PFNA") %>%
  rbind(mim_res2 %>% 
          dplyr::select(omic_layer:feature_name, EntrezGeneSymbol, 
                        HR_mo:exp_conf_low_mo, p.value_mo) %>%
          rename(estimate = HR_mo,
                 conf_low = exp_conf_low_mo,
                 conf_high = exp_conf_high_mo,
                 p_value = p.value_mo) %>%
          mutate(type = "MIC"))

dummy2 <- data.frame(type = c("PFNA", "MIC"), Z= c(0, 1))  
  
(coef_plot <- mim_res_l %>%
   ggplot(aes(x = reorder(EntrezGeneSymbol,estimate), 
              y = estimate)) + 
   geom_errorbar(aes(ymin = conf_low , 
                     ymax = conf_high), 
                 width = 0) + 
   geom_point() + 
   # scale_color_manual(values = c("grey60", "black")) +
   coord_flip() + 
   # scale_y_continuous(limits = c(-1.75, 3)) +
   facet_grid(~factor(type, levels=c('PFNA','MIC')),
              scales = "free") +
   geom_hline(data = dummy2, aes(yintercept = Z), linetype = 2, color = "grey50") +
   ylab(" β (95% CI)        HR (95% CI) ") +
   theme(
     axis.title.y = element_blank(),
     # axis.title.x = element_blank(),
     # strip.text.x = element_blank(), 
     panel.background = element_rect(fill="white"), 
     strip.background = element_rect(fill = "white"),
     legend.position = "none",
     strip.text.y = element_text(angle = 0, hjust = 0)))
  # +
  #  scale_color_brewer(name = "Direction", palette = "Dark2" ))

#Save
ggsave(coef_plot, 
       filename = here::here(dir_figure, "coef plot.jpeg"), 
       width = 8, height = 5)
```

