---
title: 'Today project'
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
```{r overall setup, include=FALSE}
source(here::here("!libraries.R"))
source(here::here("!directories.R"))
source(here::here("!load_clean_data.R"))

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


# 1. Data Description
```{r child="0_Data Processing.Rmd"}

```

# 2. Descriptive Statistics
```{r child="1_Descriptive Statistics.Rmd"}

```

# 3. Correlation Plot
```{r child="2_Correlation.Rmd"}

```

# 4. Regression Methods
**This analysis relies on the broom and purrr packages in R and you can find more information here https://cran.r-project.org/web/packages/broom/vignettes/broom_and_dplyr.html, especially how the nest/unnest functions in tidyr and the map function in purrr work.**
```{r child="3_Regression Methods.Rmd"}

```

# 5. Mixture analysis Methods
```{r child="4_Mixture analysis Methods.Rmd"}

```

