---
title: 'Example Project'
subtitle: "Mixture analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"

output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{css, echo=FALSE}
pre {
  max-height: 200px;
  overflow-: auto;
}

```


```{r mixture analysis setup, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE)
source(here::here("!libraries.R"))
source(here::here("!directories.R"))
source(here::here("!load_cleaned_data.R"))
source(here::here("g_prior_sel_logistic_function.R"))
```

## Mixture Analysis Overview
**This part contains introduced an example of mixture analysis using qgcomp package in R**

## Mixture analysis using qgcomp package
**Example Model: binary nafld outcome ~ all plasma pfas + covars**
```{r qgcomp, echo=TRUE}
## Step1. Define variables----
# covariates
covars <- c("race_binary", 
            "smoke_0", 
            "age_0", 
            "sex", 
            "parents_income_0")

# categorical outcomes(two categories or more)
cat_outcomes <- c("nafld_nash_mul_0", "nafld_di_0","steatgrd_mul_0", "bhepa_0",
                   "dyslipid_di_0")

# continuous outcomes
cont_outcomes <- c("alt_0", "ast_0")
# plasma pfas'

## rename pfas
plasma_pfas <- colnames(data)[grepl("imputed",colnames(data))]

data1<- data %>% 
  rename_all(~str_replace_all(., "_untargeted_plasma_0_imputed", ""))

# extract plasma pfas name
plasma_pfas1 <- setdiff(colnames(data1), c(covars, cat_outcomes, cont_outcomes , "key"))

## or
# plasma_pfas <- c("pfda
#                  "pf_hx_s",
#                  "pf_hp_s",
#                  "pfna",
#                  "pfoa",
#                  "pfos")

## Step2. Mixture analysis using qgcomp()

#### qgcomp-----
qgcomp_output <- qgcomp.noboot(as.formula(paste("nafld_di_0~",
                                                str_c(plasma_pfas1, collapse = "+") ,
                                                "+",
                                                str_c(covars, collapse = "+"))), # Covariates - same as MLR model
                               expnms=plasma_pfas1, # Name of Mixtures
                               data=data1,
                               family=binomial(), # family=binomial() for logistic
                               q = 3)

print("qgcomp output")
qgcomp_output 
```

## Visualization - Weighted Plot
```{r Visualization Weighted Plot}
## Step3. View Models --------------

### weighted plot----

plot(qgcomp_output, cex = 1)

### saving plot-----
# png(fs::path(dir_figure,
#              "3_weighted_plot_gcomp_nafld.png"),
#     width = 4000, height = 2000, res = 350)
# plot(qgcomp_output)
# dev.off()

```

## Visualization - Weighted Plot
```{r visualization coefficient plot}

### coefficient plot----
coef <- data.frame(qgcomp_output$fit$coefficients) %>% 
  rownames_to_column("Predictor") %>%
  filter(Predictor %in% plasma_pfas1) %>%
  rename('Log Odds Ratio' = qgcomp_output.fit.coefficients) %>%
  mutate(direction = ifelse(`Log Odds Ratio` > 0, "pos", "neg"),
         direction = factor(direction, levels = c("pos", "neg")))

# change the name of the predictor
coef1 <- coef %>% mutate(Predictor = case_when(
  grepl("pfda", Predictor) ~ "PFDA",
  grepl("pfos", Predictor) ~ "PFOS",
  grepl("pfna", Predictor) ~ "PFNA",
  grepl("pf_hx_s", Predictor) ~"PFHxS",
  grepl("pfoa", Predictor) ~ "PFOA",
  grepl("pf_hp_s", Predictor) ~ "PFHpS"
))

p <- ggplot(coef1,aes(Predictor, `Log Odds Ratio`,
                      fill = direction)) + 
  geom_bar(stat = "identity", show.legend = FALSE) + 
  ggtitle("Coefficient plot(Mixture Analysis)") +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = 2, color = "black") +
  geom_text(aes(label = round(`Log Odds Ratio`,2)), hjust= -0.05) +
  theme(axis.text = element_text(size = 15),
        text = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black"),
        panel.background = element_rect(fill="white"),
        strip.background = element_rect(fill = "white")
        )

p
### saving coefficient plot----
# ggsave(p, 
#        filename = fs::path(dir_figure,
#                            "3_coef_plot_qgcomp.jpeg"),
#        width = 7,
#        height = 4)
```
